=== golden-gecko/WarGAME/bin/xml/wargame_schema.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Resources -->

	<xs:simpleType name="ResourceAmountType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FINITE" />
			<xs:enumeration value="INFINITE" />
			<xs:enumeration value="RESTORE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ResourcePositionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EXACT" />
			<xs:enumeration value="EVERYWHERE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ResourceSizeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOX" />
			<xs:enumeration value="CIRCLE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="resource">
		<xs:sequence>
			<xs:element name="amount" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="type" type="ResourceAmountType" use="required" />
					<xs:attribute name="speed" type="xs:float" />
					<xs:attribute name="value" type="xs:float" />
				</xs:complexType>
			</xs:element>
			<xs:element name="position" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="type" type="ResourcePositionType" use="required" />
					<xs:attribute name="x" type="xs:float" />
					<xs:attribute name="y" type="xs:float" />
					<xs:attribute name="z" type="xs:float" />
				</xs:complexType>
			</xs:element>
			<xs:element name="size" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="type" type="ResourceSizeType" use="required" />
					<xs:attribute name="radius" type="xs:float" />
					<xs:attribute name="x" type="xs:float" />
					<xs:attribute name="y" type="xs:float" />
					<xs:attribute name="z" type="xs:float" />
				</xs:complexType>
			</xs:element>
			<xs:element name="mesh" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="material" type="xs:string" />
					<xs:attribute name="x" type="xs:float" />
					<xs:attribute name="y" type="xs:float" />
					<xs:attribute name="z" type="xs:float" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="resources">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="resource" type="resource" minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== golden-gecko/WarGAME/bin/xml/wargame_xml.xml
<?xml version="1.0" encoding="utf-8"?>

<root xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="wargame_schema.xsd">

	<resources>

		<resource name="Energy">
			<amount type="INFINITE" />
			<position type="EVERYWHERE" />
		</resource>

		<resource name="Green Crystal">
			<amount type="FINITE" value="20000.0" />
			<position type="EXACT" x="85.0" z="75.0" />
			<size type="BOX" x="2.0" z="2.0" />
			<mesh name="green_crystal.mesh" x="1.0" y="1.0" z="1.0" />
		</resource>

		<resource name="Green Crystal">
			<amount type="FINITE" value="50000.0" />
			<position type="EXACT" x="55.0" z="78.0" />
			<size type="BOX" x="52.0" z="4.0" />
			<mesh name="green_crystal.mesh" material="green_crystal" x="2.0" y="2.0" z="2.0" />
		</resource>

		<resource name="Red Crystal">
			<amount type="RESTORE" speed="5.0" value="1000.0" />
			<position type="EXACT" x="25.0" z="78.0" />
			<size type="CIRCLE" radius="5.0" />
			<mesh name="red_crystal.mesh" material="red_crystal" x="1.2" y="1.2" z="1.2" />
		</resource>

		<resource name="Iron Ore">
			<amount type="FINITE" value="10500.0" />
			<position type="EXACT" x="85.0" y="10.0" z="75.0" />
			<size type="CIRCLE" radius="50.0" />
			<mesh name="iron_ore.mesh" x="1.0" y="1.0" z="1.0" />
		</resource>

		<resource name="Metal" />

		<resource name="Oil">
			<amount type="RESTORE" speed="0.5" value="500.0" />
			<position type="EXACT" x="85.0" y="10.0" z="75.0" />
			<size type="CIRCLE" radius="50.0" />
			<mesh name="oil.mesh" x="1.0" y="1.0" z="1.0" />
		</resource>

		<resource name="Fuel" />

	</resources>

</root>
